### ISSUE TITLE
Examples needs a proper frame-buffered example

### ISSUE THREAD

**Issue by ratchetfreak** [toomuchvoltage/GAL#1]
Using a single command allocator and waiting for it and resetting it each frame is not recommended.

Instead one should create multiple CommandAllocators and round robin them. (waiting on the fence set after one of its commandLists was last used before resetting it)

You should also add facilities to wait on a fence for a value *other* than the current one.

**Comment by toomuchvoltage** [comment]
Hi ratchetfreak, thanks for dropping by... and yes! I was actually gonna get to it as part of the more advanced examples -- since the introductory ones on Microsoft's GitHub account simply use only one allocator -- but you just bumped up the priority :)

Regarding fence values, there will be as many (to wait on) as there will be frames/command-allocators... just like the DX12 examples.

**Comment by ratchetfreak** [comment]
To add to our little IRC chat. I envision fence use to be something like

```
struct FencedCommandAllocator {
    uint64 fenceValue;
    CommandAllocator* allocator;
};

FencedCommandAllocator[NbAllocators] allocators; 
uint allocatorIndex=0;

void render(){
    CommandAllocator* allocator = allocators[allocatorIndex];
    fence->waitFor(allocators[allocatorIndex].fenceValue);
    //now we can use allocator
    allocator->Reset();

    cmdList->Reset(allocator, pso);

    //...

    cmdList->Close();

    cmdQue->ExecuteList(cmdList);
    swapChain->Present();

    allocators[allocatorIndex].fenceValue = fence.val;
    cmdQue->Signal(fence); //maybe return which value will be the trigger?

    allocatorIndex++;
    if(allocatorIndex >= NbAllocators)
        allocatorIndex=0;
}
```

**Comment by toomuchvoltage** [comment]
I'm cooking up something nice... I'll actually bring it forth in a bit and we can refine it even more!

**Comment by toomuchvoltage** [comment]
Okay! So it's finally here.... as you suggested I've added multi-frame-buffering support to all examples and the API. In fact, as you suggested, I think this was a necessary addition as otherwise things would have been quite wasteful.

And as you suggested fence values are bundled together with command allocator objects.

Now here's where things start to be interesting. I simply decided to keep one Fence object, as you really need just one fence and one event... same as the Microsoft GitHub examples. However, there's a new function instead of wait() and it's signalAndWait(...). This function takes an optional 3rd parameter waitNow (false by default.) If waitNow is true, it performs a signal-and-immediate-wait... if not, it performs a signal-and-defer-wait-till-next-round. The actual number crunching of fence-wait values and the next-fence value is kept out of view inside the signalAndWait(...) call.

This way, we have full multi-frame-buffering, the concept of one-allocator-per-frame and proper fencing/signalling is preserved and nitty-gritty number crunching regarding actual fence values is kept out of sight!

Also, if you wish to get the next-fence value, just simply look at Fence->fenceValue. The next signalAndWait(...) call will signal using that value.

Let me know what you think :)

Cheers,
Baktash.
